version: "3"
services:
  mysql:
    image: "mysql:5.6"
    ports:
      - "3306:3306"
    enviornment:
      - MYSQL_ROOT_PASSWORD: 123456
      - MYSQL_DATABASE: embryoai_system_db
    depends_on:
      embryoai-sys:
        condition: service_healthy
    volumes:
      - $DB_DIR:/var/lib/mysql
      - sql/embryoai_system_db_1_0.sql:/docker-entrypoint-initdb.d/embryoai_system_db_1_0.sql
  embryoai-sys:
    build: .
    ports:
      - "6001:6001"
    volumes:
      - $CAPTURE_DIR:/captures
  embryoai-image:
    build: nginx-docker/
    ports:
      - "80:80"
    volumes:
      - $CAPTURE_DIR:/usr/share/nginx/html