version: "3"
services:
  # mysql:
  #  image: "mysql:5.6"
  #  ports:
  #    - "3306:3306"
  #  environment:
  #    - MYSQL_ROOT_PASSWORD:123456
  #    - MYSQL_DATABASE:embryoai_system_db
  #  volumes:
  #    - $DB_DIR:/var/lib/mysql
      # - ./sql/embryoai_system_db_1_0.sql:/docker-entrypoint-initdb.d/embryoai_system_db_1_0.sql

  embryoai-sys:
    build: .
    ports:
      - "6001:6001"
    volumes:
      - $CAPTURE_DIR:/captures

  embryoai-image:
    build: nginx-docker/
    ports:
      - "8085:80"
    volumes:
      - $CAPTURE_DIR:/usr/share/nginx/html