version: "3"
services:
  mysql:
    image: "mysql:5.6"
  embryoai-sys:
    build: .
    ports:
      - "6001:6001"
    volumes:
      - $CAPTURE_DIR:/captures
  embryoai-image:
    build: nginx-docker/
    ports:
      - "80:80"
    volumes:
      - $CAPTURE_DIR:/usr/share/nginx/html