dev:
  SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:123456@39.104.173.18:3306/embryoai_system_db_dev?charset=utf8"
  SQLALCHEMY_POOL_RECYCLE: 3
  SQLALCHEMY_POOL_SIZE: 100
  SQLALCHEMY_POOL_TIMEOUT: 3
  SQLALCHEMY_MAX_OVERFLOW: 300
  SQLALCHEMY_COMMIT_ON_TEARDOWN: true
  SEND_FILE_MAX_AGE_DEFAULT: 1
  PORT: 6001
  DEBUG: false
  THREADED: true
  LOGGER_FILE: "./embryoai.log"
  SECRET_KEY: "123456"
  JOBS:
    - id: "embryo_job"
      func: "task.embryo_task:run"
      trigger: "interval"
      seconds: 60
    - id: "collect_time_job"
      func: "task.collect_time_task:run"
      trigger: "interval"
      seconds: 60
  SCHEDULER_API_ENABLED: true

  EMBRYOAI_IMAGE_ROOT: "../captures/"
  FINISHED_JSON_FILENAME: "finished_cycles.json"
  CYCLE_PROCESS_FILENAME: "process_state.json"
  DISH_STATE_FILENAME: "dish_state.json"
  FINISHED_CYCLES: "finished_cycles.json"
  EMBRYO_FOCUS_DIRNAME: "focus"
  ACTIVE_TIMEOUT: 3600
  CASCADE_TEMPLATE: "embryo_cascade.xml"
  NO_EMBRYO_IMAGE_URL: "cv/embryo_not_found.jpg"

  KERAS_MODEL_NAME: "embryo_model.h5"
  EMBRYO_PREDICT_SIZE: 200

  STATIC_NGINX_IMAGE_URL: http://39.104.173.18:8085
  PATIENT_INFO_UP_URL: "http://localhost:8086/api/v1.0/receivePatientInfo"
  PROCEDURE_INFO_UPDATE_URL: "http://localhost:8086/api/v1.0/updateProcedure"
  MILESTONE_INFO_UP_URL: "http://localhost:8086/api/v1.0/milestone"

  ORGAN_REGISTER_URL: "http://localhost:8086/api/v1.0/organization/register"  #机构注册到云端接口
  ORGAN_JSON_FILENAME: "organization.json"
stage:
  SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:123456@39.104.173.18:3306/embryoai_system_db?charset=utf8"
  SQLALCHEMY_POOL_RECYCLE: 3
  SQLALCHEMY_POOL_SIZE: 100
  SQLALCHEMY_POOL_TIMEOUT: 3
  SQLALCHEMY_MAX_OVERFLOW: 300
  SQLALCHEMY_COMMIT_ON_TEARDOWN: true
  SEND_FILE_MAX_AGE_DEFAULT: 1
  PORT: 6001
  DEBUG: false
  THREADED: true
  LOGGER_FILE: "./embryoai.log"
  SECRET_KEY: "123456"
  JOBS:
    - id: "embryo_job"
      func: "task.embryo_task:run"
      trigger: "interval"
      seconds: 300
    - id: "collect_time_job"
      func: "task.collect_time_task:run"
      trigger: "interval"
      seconds: 300
  SCHEDULER_API_ENABLED: true

  EMBRYOAI_IMAGE_ROOT: "/captures/"
  FINISHED_JSON_FILENAME: "finished_cycles.json"
  CYCLE_PROCESS_FILENAME: "process_state.json"
  DISH_STATE_FILENAME: "dish_state.json"
  FINISHED_CYCLES: "finished_cycles.json"
  EMBRYO_FOCUS_DIRNAME: "focus"
  ACTIVE_TIMEOUT: 3600
  CASCADE_TEMPLATE: "embryo_cascade.xml"
  NO_EMBRYO_IMAGE_URL: "cv/embryo_not_found.jpg"

  KERAS_MODEL_NAME: "embryo_model.h5"
  EMBRYO_PREDICT_SIZE: 200

  STATIC_NGINX_IMAGE_URL: http://39.104.173.18:8085

  PATIENT_INFO_UP_URL: "http://39.104.173.18:8086/api/v1.0/receivePatientInfo"
  PROCEDURE_INFO_UPDATE_URL: "http://39.104.173.18:8086/api/v1.0/updateProcedure"

  ORGAN_REGISTER_URL: "http://39.104.173.18:8086/api/v1.0/organization/register"  #机构注册到云端接口
  ORGAN_JSON_FILENAME: "organization.json"

prod:
  SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:123456@localhost:3306/embryoai_system_db?charset=utf8"
  SQLALCHEMY_POOL_RECYCLE: 3
  SQLALCHEMY_POOL_SIZE: 100
  SQLALCHEMY_POOL_TIMEOUT: 3
  SQLALCHEMY_MAX_OVERFLOW: 300
  SQLALCHEMY_COMMIT_ON_TEARDOWN: true
  SEND_FILE_MAX_AGE_DEFAULT: 1
  PORT: 6001
  DEBUG: false
  THREADED: true
  LOGGER_FILE: "./embryoai.log"
  SECRET_KEY: "123456"
  JOBS:
    - id: "embryo_job"
      func: "task.embryo_task:run"
      trigger: "interval"
      seconds: 900
    - id: "collect_time_job"
      func: "task.collect_time_task:run"
      trigger: "interval"
      seconds: 300
  SCHEDULER_API_ENABLED: true

  EMBRYOAI_IMAGE_ROOT: "" # 实际生产环境的图像采集路径
  FINISHED_JSON_FILENAME: "finished_cycles.json"
  CYCLE_PROCESS_FILENAME: "process_state.json"
  DISH_STATE_FILENAME: "dish_state.json"
  FINISHED_CYCLES: "finished_cycles.json"
  EMBRYO_FOCUS_DIRNAME: "focus"
  ACTIVE_TIMEOUT: 3600
  CASCADE_TEMPLATE: "embryo_cascade.xml"
  NO_EMBRYO_IMAGE_URL: "cv/embryo_not_found.jpg"

  KERAS_MODEL_NAME: "embryo_model.h5"
  EMBRYO_PREDICT_SIZE: 200

  STATIC_NGINX_IMAGE_URL: "" # 实际生产环境的nginx地址

  PATIENT_INFO_UP_URL: "" # 实际生产环境患者信息同步云端接口地址
  PROCEDURE_INFO_UPDATE_URL: "" # 实际生产环境患者信息同步云端接口地址

  ORGAN_REGISTER_URL: ""  #实际生成环境机构注册到云端接口地址
  ORGAN_JSON_FILENAME: "organization.json"